# Generated by Django 3.1.4 on 2021-01-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
