# Generated by Django 3.1.4 on 2021-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0002_pic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='image',
        ),
    ]
