# Generated by Django 3.1.4 on 2021-01-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
