# Generated by Django 3.1.4 on 2021-01-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0005_remove_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='pic',
            name='etnia',
            field=models.CharField(choices=[('white', 'Caucásico'), ('afro', 'Afrodecendiente'), ('asian', 'Asiatico'), ('arab', 'Arabe')], default='white', max_length=100),
        ),
    ]
